language: python
python:
  - "3.6"
install:
  - pip3 install .
script:
  - python3 test.py
  - echo "Tests are executed"
deploy:
  provider: pypi
  user: venkat214
  password:
    secure: lA/arFUbPOqnhsoUNS05ZQEbx2mCFNWuU3U1apVI8Mum1/1LzpGehwswbOaOkOUQiuBv1qwmZh5/zk5yrwBwl385PVzxbxTwJpla9qVnPlWWbbYyXJFW8laiAATTUc6oyOlxA0SMxM4hIQy2OocNzRZhQw5Vgu6CA0JUdjBn0m/9cYYdzQCgGedlTIwGEe20EgpbIwRruJfG12bqDVOwoXQyY0ZrskvbW13mt0OV/FOsc/mjoGACGkYQ2a0ITrafWwrFBUxjwIsnV9ELsfHp8xaQkbr4jpzdB/wzFUuCTKjUhPHibM6WmY7zgML8Jm/giI8PG3aVwUMBR+gbYCvXx5Z4ofkJZkz8Q3PnWjrz5dIFwbjr0RdtanYbvIZq9Gu2WMUFiED7LaqMJ1D1y5jmUk+xrrYiwxSUICz7apo0r5FaG12ZjHHt7fNmW5a48/9MnlbZNlPiU/nsY2N+cA5PzVIOFjizvz1j72gDN93Sd0U3j2P5L1GiqziMO3AYeIJWfDaz6qw17UYhvzMcpH73PWR1c3onxdeRXUNRZi5v5b84wmHNPR2MLwxD4Pw+fMbHocJUotVwPj/A2sWjOFHkRDbjNu7rnKQttGzdW4BUKLz+vRCRevu2ZGNPYGjkxQaKrs7KBsgqa+EbV0Nve/9LzwaVCa/rowg8JQlcVZN7ntg="
  distributions: sdist bdist_wheel
  skip_cleanup: true
  true:
    branch: master
    tags: false
